@RSS_API_HostAddress = http://localhost:5270

GET {{RSS_API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{RSS_API_HostAddress}}/substack/today
Accept: application/json

###

GET {{RSS_API_HostAddress}}/substack/today?date=2026-07-09&timeZone=Europe/London
Accept: application/json

###
