@RSS_API_HostAddress = http://localhost:5270
@SubstackApiKey = replace-with-your-api-key

GET {{RSS_API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{RSS_API_HostAddress}}/substack/refresh
Accept: application/json
X-API-Key: {{SubstackApiKey}}

###

GET {{RSS_API_HostAddress}}/substack/today
Accept: application/json
X-API-Key: {{SubstackApiKey}}

###

GET {{RSS_API_HostAddress}}/substack/status
Accept: application/json
X-API-Key: {{SubstackApiKey}}

###

GET {{RSS_API_HostAddress}}/substack/post-detail?id=replace-with-post-id
Accept: application/json
X-API-Key: {{SubstackApiKey}}

###
